### ISSUE TITLE
Error when creating normal playlists

### ISSUE THREAD

**Issue by dashbad** [mhite/swinsian2itlxml#2]
A bug this time.

When running the script I was receiving an error around concatenating a str and int object at line 260:

> for x, row in enumerate(rows, x+1):

This seems to be because x is a str when it is passed to enumerate. I've fixed this by simply inserting:

x = int(x) at line 259

I haven't had the chance to work out why this had broken or whether this is the best solution so I haven't created a pull request. My Python/programming knowledge is quite limited

**Comment by mhite** [comment]
Issue fixed -- it was a corner case that I handled very poorly. I've checked the fix into the `amory` branch and I will merge it into master soon. Feel free to check out that branch and give it a spin in the meantime.

**Comment by mhite** [comment]
FYI, the fix is merged into master. I've deleted the test branch.
